"""Initial migration

Revision ID: 5411819d1de1
Revises: 62ed28e3d924
Create Date: 2025-02-21 17:00:19.854048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5411819d1de1'
down_revision: Union[str, None] = '62ed28e3d924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint('users_firstname_key', 'users', type_='unique')
    op.drop_constraint('users_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.create_unique_constraint('users_firstname_key', 'users', ['firstname'])
    op.alter_column('users', 'token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
