"""Initial migration

Revision ID: 62ed28e3d924
Revises: 3b2fb438e3b7
Create Date: 2025-02-21 12:20:05.646035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ed28e3d924'
down_revision: Union[str, None] = '3b2fb438e3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=False))
    op.alter_column('users', 'token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('users_lastname_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['firstname'])
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_lastname_key', 'users', ['lastname'])
    op.alter_column('users', 'token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
